# Generated by Django 4.2.6 on 2023-10-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
