# Generated by Django 4.2.6 on 2023-10-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_remove_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
